name: Build and Test verval solution

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Kód letöltése
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # .NET SDK telepítése
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      # Függőségek visszaállítása
      - name: Restore dependencies
        run: dotnet restore verval.sln
      
      # Solution buildelése
      - name: Build solution
        run: dotnet build verval.sln --configuration Release --no-restore
      
      # Tesztek futtatása és coverage gyűjtés
      - name: Run tests with coverage
        run: dotnet test test/DatesAndStuff.Tests/DatesAndStuff.Tests.csproj --configuration Release --no-build --collect:"XPlat Code Coverage" --settings coverlet.runsettings
      
      # ReportGenerator telepítése
      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool
      
      # HTML riport generálása
      - name: Generate coverage report
        run: reportgenerator -reports:"test/DatesAndStuff.Tests/TestResults/*/coverage.cobertura.xml" -targetdir:"coveragereport" -reporttypes:Html
      
      # Artifact feltöltése
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coveragereport/